// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWECKoBB5OE149L6QpdtCYNojfC9bA_Q',
    appId: '1:147567794739:web:2e1365edb73540c968a146',
    messagingSenderId: '147567794739',
    projectId: 'tranporte-rural',
    authDomain: 'tranporte-rural.firebaseapp.com',
    storageBucket: 'tranporte-rural.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjUoVd5HoTU00GTqNx6AK8jyhxyAz9is',
    appId: '1:147567794739:android:7b623e65cd12c2d668a146',
    messagingSenderId: '147567794739',
    projectId: 'tranporte-rural',
    storageBucket: 'tranporte-rural.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kX_M0meXlIfkggWPV3DPc7EtWsxznPk',
    appId: '1:147567794739:ios:c1100b5abc22a82f68a146',
    messagingSenderId: '147567794739',
    projectId: 'tranporte-rural',
    storageBucket: 'tranporte-rural.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_kX_M0meXlIfkggWPV3DPc7EtWsxznPk',
    appId: '1:147567794739:ios:c1100b5abc22a82f68a146',
    messagingSenderId: '147567794739',
    projectId: 'tranporte-rural',
    storageBucket: 'tranporte-rural.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVWECKoBB5OE149L6QpdtCYNojfC9bA_Q',
    appId: '1:147567794739:web:36be01844517fc2568a146',
    messagingSenderId: '147567794739',
    projectId: 'tranporte-rural',
    authDomain: 'tranporte-rural.firebaseapp.com',
    storageBucket: 'tranporte-rural.firebasestorage.app',
  );
}
